ForceTestingService/ForceTestingService.WEB/Controllers/StudentTestController.cs
using System.Threading.Tasks;
using ForceTestingService.ApplicationCore.Interfaces;
using ForceTestingService.ApplicationCore.Models;
using ForceTestingService.Infrastructure.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace ForceTestingService.WEB.Controllers
{
    [Authorize(Roles = "student")]
    public class StudentTestController : Controller
    {
        private readonly UserManager<User> _userManager;
        private readonly IStudentTestService _studentTestService;

        public StudentTestController(UserManager<User> userManager, IStudentTestService studentTestService)
        {
            _userManager = userManager;
            _studentTestService = studentTestService;
        }

        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> GetTests()
        {
            var user = await _userManager.GetUserAsync(HttpContext.User);
            var model = await _studentTestService.CreateStudentTestsListForUserAsync(user);
            return View(model);
        }

        public async Task<IActionResult> ViewTestResults(int testBaseId)
        {
            var user = await _userManager.GetUserAsync(HttpContext.User);
            var model = await _studentTestService.GetTestResultsForUserAsync(user, testBaseId);
            return View(model);
        }

        public async Task<IActionResult> PassTest(int testBaseId)
        {
            var user = await _userManager.GetUserAsync(HttpContext.User);
            var model = await _studentTestService.CraftRandomTestFromTestBaseAsync(user, testBaseId);
            if (model == null)
            {
                return RedirectToAction("ViewTestResults", new { testBaseId });
            }

            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> PassTest(CraftedTest craftedTest)
        {
            craftedTest.User = await _userManager.GetUserAsync(HttpContext.User);
            await _studentTestService.SubmitTestAsync(craftedTest);
            return RedirectToAction(nameof(GetTests));
        }
    }
}

ForceTestingService/ForceTestingService.WEB/Views/StudentTest/GetTests.cshtml
@model IEnumerable<ForceTestingService.ApplicationCore.Models.StudentTest>

<h1>List of all available tests</h1>

<p>
    <a asp-action="Index">Go Back</a>
</p>
<table class="table">
    <thead>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.TestName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SubjectName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TopicName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NumOfQuestions)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AmountOfSeconds)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NumOfTriesLeft)
        </th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    @foreach (var item in Model)
    {
        <tr @Html.Raw(!item.IsPassed?"":"class='bg-success'")>
            <td>
                @Html.DisplayFor(modelItem => item.TestName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SubjectName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TopicName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NumOfQuestions)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AmountOfSeconds)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NumOfTriesLeft)
            </td>
            <td>
                <a asp-action="ViewTestResults" asp-route-testbaseid="@item.TestBaseId">View Test Results</a> |
                @if (item.NumOfTriesLeft > 0)
                {
                    <a asp-action="PassTest" asp-route-testbaseid="@item.TestBaseId">Pass Test</a> 
                }
                else
                {
                    <a style="pointer-events: none; cursor: default; background-color: lightcoral">Pass Test</a> 
                }

            </td>
        </tr>
    }
    </tbody>
</table>

ForceTestingService/ForceTestingService.WEB/Views/StudentTest/Index.cshtml
<h2>Test main menu</h2>

<a asp-action="GetTests">Show All Available Tests</a>
<br />

<br />
<a asp-controller="Home" asp-action="Index">Go back</a>

ForceTestingService/ForceTestingService.WEB/Views/StudentTest/PassTest.cshtml
@using System.Linq
@model ForceTestingService.ApplicationCore.Models.CraftedTest

<h1>Test</h1>

<form method="post" asp-controller="StudentTest" asp-action="PassTest">
    <div>
        <input asp-for="Date" type="hidden" value="@Model.Date" />
        <input asp-for="Score" type="hidden" value="@Model.Score" />
        <input asp-for="TestBaseDto.NumOfQuestions" type="hidden" value="@Model.TestBaseDto.NumOfQuestions" />
        <input asp-for="TestBaseDto.TopicId" type="hidden" value="@Model.TestBaseDto.TopicId" />
        <input asp-for="TestBaseDto.Id" type="hidden" value="@Model.TestBaseDto.Id" />
        <input asp-for="TestBaseDto.TopicName" type="hidden" value="@Model.TestBaseDto.TopicName" />
        <input asp-for="TestBaseDto.AmountOfSeconds" type="hidden" value="@Model.TestBaseDto.AmountOfSeconds" />
        <input asp-for="TestBaseDto.NumOfTries" type="hidden" value="@Model.TestBaseDto.NumOfTries" />
        <input asp-for="TestBaseDto.Name" type="hidden" value="@Model.TestBaseDto.Name" />
    </div>
    
    <div>
        <div class="question">
            @for (int i = 0; i < Model.Questions.Count(); i++)
            {
                <input name="questions[@i].TopicId" type="hidden" value="@Model.Questions.ElementAt(i).TopicId" />
                <input name="questions[@i].TaskInfo" type="hidden" value="@Model.Questions.ElementAt(i).TaskInfo" />
                <input name="questions[@i].TopicName" type="hidden" value="@Model.Questions.ElementAt(i).TopicName" />
                <input name="questions[@i].Id" type="hidden" value="@Model.Questions.ElementAt(i).Id" />
                <br />
                @Model.Questions.ElementAt(i).TaskInfo
                <br />

                for (int j = 0; j < @Model.Questions.ElementAt(i).Answers.Count; j++)
                {
                    <input name="questions[@i].Answers[@j].Id" type="hidden" value="@Model.Questions.ElementAt(i).Answers.ElementAt(j).Id" />
                    <input name="questions[@i].Answers[@j].QuestionId" type="hidden" value="@Model.Questions.ElementAt(i).Answers.ElementAt(j).QuestionId" />
                    <input name="questions[@i].Answers[@j].Text" type="hidden" value="@Model.Questions.ElementAt(i).Answers.ElementAt(j).Text" />

                    <input type="checkbox" name="questions[@i].Answers[@j].IsCorrect" value="true" />
                    @Model.Questions.ElementAt(i).Answers.ElementAt(j).Text<br />
                }
            }
        </div>
    </div>

    <div>
        <input type="submit" value="Submit Test" />
    </div>
</form>

ForceTestingService/ForceTestingService.WEB/Views/StudentTest/ViewTestResults.cshtml
@model IEnumerable<ForceTestingService.ApplicationCore.DTO.TestResultDto>

<h1>Results for selected test:</h1>

<p>
    <a asp-action="GetTests">Go back</a>
</p>
<table class="table">
    <thead>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Date)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Score)
        </th>
    </tr>
    </thead>
    <tbody>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Date)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Score)
            </td>
        </tr>
    }
    </tbody>
</table>