ForceTestingService/ForceTestingService.WEB/Controllers/SubjectController.cs
using System.Threading.Tasks;
using ForceTestingService.ApplicationCore.DTO;
using ForceTestingService.ApplicationCore.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace ForceTestingService.WEB.Controllers
{
    [Authorize(Roles = "teacher")]
    public class SubjectController : Controller
    {
        private readonly ISubjectService _subjectService;
        public SubjectController(ISubjectService subjectService)
        {
            _subjectService = subjectService;
        }

        public async Task<IActionResult> Index()
        {
            var model = await _subjectService.GetAllSubjectsAsync();
            return View(model);
        }

        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(SubjectDto subjectDto)
        {
            if (ModelState.IsValid)
            {
                await _subjectService.CreateSubjectAsync(subjectDto);
                return RedirectToAction(nameof(Index));
            }
            return View(subjectDto);
        }

        public async Task<IActionResult> Edit(int id)
        {
            var subjectDtoToEdit = await _subjectService.GetSubjectByIdAsync(id);
            return View(subjectDtoToEdit);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(SubjectDto subjectDto)
        {
            if (ModelState.IsValid)
            {
                await _subjectService.UpdateSubjectAsync(subjectDto);
                return RedirectToAction(nameof(Index));
            }
            return View(subjectDto);
        }

        public async Task<IActionResult> Delete(int id)
        {
            var subjectDtoToDelete = await _subjectService.GetSubjectByIdAsync(id);
            return View(subjectDtoToDelete);
        }
        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await _subjectService.DeleteSubjectByIdAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

ForceTestingService/ForceTestingService.WEB/Views/Subject/Create.cshtml
@model ForceTestingService.ApplicationCore.DTO.SubjectDto

<h2>Create new Subject</h2>
<form method="post" asp-controller="Subject" asp-action="Create">
    <div asp-validation-summary="ModelOnly"></div>
    <div>
        <label asp-for="Name"></label><br />
        <input asp-for="Name" />
        <span asp-validation-for="Name"></span>
    </div>
    <div>
        <input type="submit" value="Create" />
    </div>
</form>

ForceTestingService/ForceTestingService.WEB/Views/Subject/Delete.cshtml
@model ForceTestingService.ApplicationCore.DTO.SubjectDto

<h1>Delete Subject</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

ForceTestingService/ForceTestingService.WEB/Views/Subject/Edit.cshtml
@model ForceTestingService.ApplicationCore.DTO.SubjectDto

<h2>Edit Subject</h2>
<form method="post" asp-controller="Subject" asp-action="Edit">
    <div asp-validation-summary="ModelOnly"></div>
    <div>
        <label asp-for="Name"></label><br />
        <input asp-for="Name" />
        <span asp-validation-for="Name"></span>
    </div>
    <div>
        <input type="submit" value="Edit" />
    </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

ForceTestingService/ForceTestingService.WEB/Views/Subject/Index.cshtml
@model IEnumerable<ForceTestingService.ApplicationCore.DTO.SubjectDto>

<h1>Subject Manager</h1>

<p>
    <a asp-action="Create">Create new Subject</a>
</p>
<table class="table">
    <thead>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a> 
            </td>
        </tr>
    }
    </tbody>
</table>
<p>
    <a asp-controller="Home" asp-action="Index">Go back</a>
</p>