ForceTestingService/ForceTestingService.WEB/Controllers/TestBaseController.cs
using System.Threading.Tasks;
using ForceTestingService.ApplicationCore.DTO;
using ForceTestingService.ApplicationCore.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ForceTestingService.WEB.Controllers
{
    [Authorize(Roles = "teacher")]
    public class TestBaseController : Controller
    {
        private readonly ITestBaseService _testBaseService;
        private readonly ITopicService _topicService;
        private readonly ITestResultService _testResultService;
        public TestBaseController(ITestBaseService testBaseService, ITopicService topicService, ITestResultService testResultService)
        {
            _testBaseService = testBaseService;
            _topicService = topicService;
            _testResultService = testResultService;
        }

        public async Task<IActionResult> Index()
        {
            var model = await _testBaseService.GetAllTestBasesAsync();
            return View(model);
        }

        public async Task<IActionResult> Create()
        {
            var topics = await _topicService.GetAllTopicsAsync();
            ViewData["TopicId"] = new SelectList(topics, "Id", "Name");
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(TestBaseDto testBaseDto)
        {
            if (ModelState.IsValid)
            {
                await _testBaseService.CreateTestBaseAsync(testBaseDto);
                return RedirectToAction(nameof(Index));
            }

            var topics = await _topicService.GetAllTopicsAsync();
            ViewData["TopicId"] = new SelectList(topics, "Id", "Name", testBaseDto.TopicId);
            return View(testBaseDto);
        }

        public async Task<IActionResult> Edit(int id)
        {
            var topics = await _topicService.GetAllTopicsAsync();
            ViewData["TopicId"] = new SelectList(topics, "Id", "Name");

            var testBaseDtoToEdit = await _testBaseService.GetTestBaseByIdAsync(id);
            return View(testBaseDtoToEdit);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(TestBaseDto testBaseDto)
        {
            if (ModelState.IsValid)
            {
                await _testBaseService.UpdateTestBaseAsync(testBaseDto);
                return RedirectToAction(nameof(Index));
            }

            var topics = await _topicService.GetAllTopicsAsync();
            ViewData["TopicId"] = new SelectList(topics, "Id", "Name", testBaseDto.TopicId);
            return View(testBaseDto);
        }

        public async Task<IActionResult> Delete(int id)
        {
            var testBaseDtoToDelete = await _testBaseService.GetTestBaseByIdAsync(id);
            return View(testBaseDtoToDelete);
        }
        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await _testBaseService.DeleteTestBaseByIdAsync(id);
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> ShowResults(int id)
        {
            var model = await _testResultService.GetTestResultsByTestBaseIdAsync(id);
            return View(model);
        }
    }
}

ForceTestingService/ForceTestingService.WEB/Views/TestBase/Create.cshtml
@model ForceTestingService.ApplicationCore.DTO.TestBaseDto

<h2>Create new Test</h2>
<form method="post" asp-controller="TestBase" asp-action="Create">
    <div asp-validation-summary="ModelOnly"></div>
    <div>
        <label asp-for="Name"></label><br />
        <input asp-for="Name" />
        <span asp-validation-for="Name"></span>
    </div>
    <div class="form-group">
        <label asp-for="TopicId" class="control-label">Topic</label>
        <select asp-for="TopicId" class="form-control" asp-items="ViewBag.TopicId"></select>
    </div>
    <div>
        <label asp-for="NumOfQuestions"></label><br />
        <input asp-for="NumOfQuestions" />
        <span asp-validation-for="NumOfQuestions"></span>
    </div>
    <div>
        <label asp-for="AmountOfSeconds"></label><br />
        <input asp-for="AmountOfSeconds" />
        <span asp-validation-for="AmountOfSeconds"></span>
    </div>
    <div>
        <label asp-for="NumOfTries"></label><br />
        <input asp-for="NumOfTries" />
        <span asp-validation-for="NumOfTries"></span>
    </div>
    <div>
        <input type="submit" value="Create" />
    </div>
</form>

ForceTestingService/ForceTestingService.WEB/Views/TestBase/Delete.cshtml
@model ForceTestingService.ApplicationCore.DTO.TestBaseDto

<h1>Delete Test</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.TopicName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.TopicName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.NumOfQuestions)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.NumOfQuestions)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.AmountOfSeconds)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.AmountOfSeconds)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.NumOfTries)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.NumOfTries)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

ForceTestingService/ForceTestingService.WEB/Views/TestBase/Edit.cshtml
@model ForceTestingService.ApplicationCore.DTO.TestBaseDto

<h2>Edit Test</h2>
<form method="post" asp-controller="TestBase" asp-action="Edit">
    <div asp-validation-summary="ModelOnly"></div>
    <div>
        <label asp-for="Name"></label><br />
        <input asp-for="Name" />
        <span asp-validation-for="Name"></span>
    </div>
    <div class="form-group">
        <label asp-for="TopicId" class="control-label">Subject</label>
        <select asp-for="TopicId" class="form-control" asp-items="ViewBag.TopicId"></select>
    </div>
    <div>
        <label asp-for="NumOfQuestions"></label><br />
        <input asp-for="NumOfQuestions" />
        <span asp-validation-for="NumOfQuestions"></span>
    </div>
    <div>
        <label asp-for="AmountOfSeconds"></label><br />
        <input asp-for="AmountOfSeconds" />
        <span asp-validation-for="AmountOfSeconds"></span>
    </div>
    <div>
        <label asp-for="NumOfTries"></label><br />
        <input asp-for="NumOfTries" />
        <span asp-validation-for="NumOfTries"></span>
    </div>
    <div>
        <input type="submit" value="Edit" />
    </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

ForceTestingService/ForceTestingService.WEB/Views/TestBase/Index.cshtml
@model IEnumerable<ForceTestingService.ApplicationCore.DTO.TestBaseDto>

<h1>Test Manager</h1>

<p>
    <a asp-action="Create">Create new Test</a>
</p>
<table class="table">
    <thead>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TopicName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NumOfQuestions)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AmountOfSeconds)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NumOfTries)
        </th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TopicName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NumOfQuestions)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AmountOfSeconds)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NumOfTries)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a> |
                <a asp-action="ShowResults" asp-route-id="@item.Id">Show student's results</a>
            </td>
        </tr>
    }
    </tbody>
</table>
<p>
    <a asp-controller="Home" asp-action="Index">Go back</a>
</p>

ForceTestingService/ForceTestingService.WEB/Views/TestBase/ShowResults.cshtml
@model IEnumerable<ForceTestingService.ApplicationCore.DTO.TestResultDto>

<h1>Test Manager</h1>

<p>
    <a asp-action="Index">Go back to list</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.StudentFullName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Date)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Score)
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.StudentFullName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Date)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Score)
                </td>
            </tr>
        }
    </tbody>
</table>