ForceTestingService/ForceTestingService.WEB/Controllers/AnswerController.cs
using System.Threading.Tasks;
using ForceTestingService.ApplicationCore.DTO;
using ForceTestingService.ApplicationCore.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace ForceTestingService.WEB.Controllers
{
    [Authorize(Roles = "teacher")]
    public class AnswerController : Controller
    {
        private readonly IAnswerService _answerService;
        private readonly IQuestionService _questionService;
        public AnswerController(IAnswerService answerService, IQuestionService questionService)
        {
            _answerService = answerService;
            _questionService = questionService;
        }

        public async Task<IActionResult> Index(int questionId)
        {
            var model = await _answerService.GetAllAnswersOfSpecificQuestionAsync(questionId);
            var question = await _questionService.GetQuestionByIdAsync(questionId);
            ViewBag.Question = question;

            return View(model);
        }

        public async Task<IActionResult> Create(int questionId)
        {
            var question = await _questionService.GetQuestionByIdAsync(questionId);
            ViewBag.Question = question;
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(AnswerDto answerDto)
        {
            if (ModelState.IsValid)
            {
                await _answerService.CreateAnswerAsync(answerDto);
                return RedirectToAction("Index", new { questionId = answerDto.QuestionId });
            }

            var question = await _questionService.GetQuestionByIdAsync(answerDto.QuestionId);
            ViewBag.Question = question;
            return View(answerDto);
        }

        public async Task<IActionResult> Edit(int id, int questionId)
        {;
            var question = await _questionService.GetQuestionByIdAsync(questionId);
            ViewBag.Question = question;

            var answerDtoToEdit = await _answerService.GetAnswerByIdAsync(id);
            return View(answerDtoToEdit);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(AnswerDto answerDto)
        {
            if (ModelState.IsValid)
            {
                await _answerService.UpdateAnswerAsync(answerDto);
                return RedirectToAction("Index", new { questionId = answerDto.QuestionId });
            }

            var question = await _questionService.GetQuestionByIdAsync(answerDto.QuestionId);
            ViewBag.Question = question;
            return View(answerDto);
        }

        public async Task<IActionResult> Delete(int id, int questionId)
        {
            var question = await _questionService.GetQuestionByIdAsync(questionId);
            ViewBag.Question = question;

            var answerDtoToDelete = await _answerService.GetAnswerByIdAsync(id);
            return View(answerDtoToDelete);
        }
        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var answerDto = await _answerService.GetAnswerByIdAsync(id);

            await _answerService.DeleteAnswerByIdAsync(id);
            return RedirectToAction("Index", new { questionId = answerDto.QuestionId });
        }
    }
}

ForceTestingService/ForceTestingService.WEB/Controllers/QuestionController.cs
using System.Threading.Tasks;
using ForceTestingService.ApplicationCore.DTO;
using ForceTestingService.ApplicationCore.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace ForceTestingService.WEB.Controllers
{
    [Authorize(Roles = "teacher")]
    public class QuestionController : Controller
    {
        private readonly IQuestionService _questionService;
        private readonly ITopicService _topicService;
        public QuestionController(IQuestionService questionService, ITopicService topicService)
        {
            _questionService = questionService;
            _topicService = topicService;
        }

        public async Task<IActionResult> Index(int topicId)
        {
            var model = await _questionService.GetAllQuestionsOfSpecificTopicAsync(topicId);
            var topic = await _topicService.GetTopicByIdAsync(topicId);
            ViewBag.Topic = topic;
            return View(model);
        }

        public async Task<IActionResult>Create(int topicId)
        {
            var topic = await _topicService.GetTopicByIdAsync(topicId);
            ViewBag.Topic = topic;
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(QuestionDto questionDto)
        {
            if (ModelState.IsValid)
            {
                await _questionService.CreateQuestionWithEmptyAnswersAsync(questionDto);
                return RedirectToAction("Index", new { topicId = questionDto.TopicId });
            }

            var topic = await _topicService.GetTopicByIdAsync(questionDto.TopicId);
            ViewBag.Topic = topic;
            return View(questionDto);
        }

        public async Task<IActionResult> Edit(int id, int topicId)
        {
            var topic = await _topicService.GetTopicByIdAsync(topicId);
            ViewBag.Topic = topic;

            var questionDtoToEdit = await _questionService.GetQuestionByIdAsync(id);
            return View(questionDtoToEdit);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(QuestionDto questionDto)
        {
            if (ModelState.IsValid)
            {
                await _questionService.UpdateQuestionAsync(questionDto);
                return RedirectToAction("Index", new { topicId = questionDto.TopicId });
            }

            var topic = await _topicService.GetTopicByIdAsync(questionDto.TopicId);
            ViewBag.Topic = topic;
            return View(questionDto);
        }

        public async Task<IActionResult> Delete(int id, int topicId)
        {
            var topic = await _topicService.GetTopicByIdAsync(topicId);
            ViewBag.Topic = topic;

            var questionDtoToDelete = await _questionService.GetQuestionByIdAsync(id);
            return View(questionDtoToDelete);
        }
        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var questionDto = await _questionService.GetQuestionByIdAsync(id);

            await _questionService.DeleteQuestionByIdAsync(id);
            return RedirectToAction("Index", new { topicId = questionDto.TopicId });
        }
    }
}

ForceTestingService/ForceTestingService.WEB/Controllers/TopicController.cs
using System.Threading.Tasks;
using ForceTestingService.ApplicationCore.DTO;
using ForceTestingService.ApplicationCore.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ForceTestingService.WEB.Controllers
{
    [Authorize(Roles = "teacher")]
    public class TopicController : Controller
    {
        private readonly ITopicService _topicService;
        private readonly ISubjectService _subjectService;
        public TopicController(ITopicService topicService, ISubjectService subjectService)
        {
            _topicService = topicService;
            _subjectService = subjectService;
        }

        public async Task<IActionResult> Index()
        {
            var model = await _topicService.GetAllTopicsAsync();
            return View(model);
        }

        public async Task<IActionResult> Create()
        {
            var subjects = await _subjectService.GetAllSubjectsAsync();
            ViewData["SubjectId"] = new SelectList(subjects, "Id", "Name");
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(TopicDto topicDto)
        {
            if (ModelState.IsValid)
            {
                await _topicService.CreateTopicAsync(topicDto);
                return RedirectToAction(nameof(Index));
            }

            var subjects = await _subjectService.GetAllSubjectsAsync();
            ViewData["SubjectId"] = new SelectList(subjects, "Id", "Name", topicDto.SubjectId);
            return View(topicDto);
        }

        public async Task<IActionResult> Edit(int id)
        {
            var subjects = await _subjectService.GetAllSubjectsAsync();
            ViewData["SubjectId"] = new SelectList(subjects, "Id", "Name");

            var topicDtoToEdit = await _topicService.GetTopicByIdAsync(id);
            return View(topicDtoToEdit);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(TopicDto topicDto)
        {
            if (ModelState.IsValid)
            {
                await _topicService.UpdateTopicAsync(topicDto);
                return RedirectToAction(nameof(Index));
            }

            var subjects = await _subjectService.GetAllSubjectsAsync();
            ViewData["SubjectId"] = new SelectList(subjects, "Id", "Name", topicDto.SubjectId);
            return View(topicDto);
        }

        public async Task<IActionResult> Delete(int id)
        {
            var topicDtoToDelete = await _topicService.GetTopicByIdAsync(id);
            return View(topicDtoToDelete);
        }
        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await _topicService.DeleteTopicByIdAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

ForceTestingService/ForceTestingService.WEB/Views/Question/Create.cshtml
@model ForceTestingService.ApplicationCore.DTO.QuestionDto

<h2>Create new Question for topic "@ViewBag.Topic.Name"</h2>
<form method="post" asp-controller="Question" asp-action="Create">
    <div asp-validation-summary="ModelOnly"></div>
    <div>
        <input asp-for="TopicId" type="hidden" value="@ViewBag.Topic.Id"/>
        <input asp-for="TopicName" type="hidden" value="@ViewBag.Topic.Name"/>
    </div>
    <div>
        <label asp-for="TaskInfo"></label><br />
        <input asp-for="TaskInfo" />
        <span asp-validation-for="TaskInfo"></span>
    </div>
    <div>
        <input type="submit" value="Create" />
    </div>
</form>

ForceTestingService/ForceTestingService.WEB/Views/Question/Delete.cshtml
@model ForceTestingService.ApplicationCore.DTO.QuestionDto

<h1>Delete Question</h1>

<h3>Are you sure you want to delete question?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.TaskInfo)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.TaskInfo)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.TopicName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.TopicName)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index" asp-route-topicId="@ViewBag.Topic.Id">Back to List</a>
    </form>
</div>

ForceTestingService/ForceTestingService.WEB/Views/Question/Edit.cshtml
@model ForceTestingService.ApplicationCore.DTO.QuestionDto

<h2>Edit Question of topic "@ViewBag.Topic.Name"</h2>
<form method="post" asp-controller="Question" asp-action="Edit">
    <div asp-validation-summary="ModelOnly"></div>
    <div>
        <input asp-for="TopicId" type="hidden" value="@ViewBag.Topic.Id"/>
        <input asp-for="TopicName" type="hidden" value="@ViewBag.Topic.Name"/>
    </div>
    <div>
        <label asp-for="TaskInfo"></label><br />
        <input asp-for="TaskInfo" />
        <span asp-validation-for="TaskInfo"></span>
    </div>
    <div>
        <input type="submit" value="Edit" />
    </div>
</form>

<div>
    <a asp-action="Index" asp-route-topicId="@ViewBag.Topic.Id">Back to List</a>
</div>

ForceTestingService/ForceTestingService.WEB/Views/Question/Index.cshtml
@model IEnumerable<ForceTestingService.ApplicationCore.DTO.QuestionDto>

<h1>Question Manager for Topic "@ViewBag.Topic.Name"</h1>

<p>
    <a asp-action="Create" asp-route-topicId="@ViewBag.Topic.Id">Create and add new Question to topic</a>
</p>
<table class="table">
    <thead>
    <tr>
        <th>
            <p>Questions Task Info</p>
        </th>
        <th>
            <p>Num of answers</p>
        </th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.TaskInfo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Answers.Count)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id" asp-route-topicId="@ViewBag.Topic.Id">Edit</a> |
                <a asp-action="Delete" asp-route-id="@item.Id" asp-route-topicId="@ViewBag.Topic.Id">Delete</a> |
                <a asp-action="Index" asp-controller="Answer" asp-route-questionid="@item.Id">Manage Answers</a>
            </td>
        </tr>
    }
    </tbody>
</table>
<p>
    <a asp-controller="Topic" asp-action="Index">Go back</a>
</p>